# Generated by Django 2.2.4 on 2019-08-15 20:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image_url', models.URLField(max_length=100)),
                ('is_authorized', models.BooleanField(default=False)),
                ('subscribers', models.ManyToManyField(blank=True, related_name='_user_subscribers_+', to='blog.User')),
                ('subscribes', models.ManyToManyField(blank=True, related_name='_user_subscribes_+', to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('image_url', models.URLField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.UUIDField(default=uuid.uuid4)),
                ('author_url', models.URLField(max_length=100)),
                ('content', models.TextField(default='')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
