# Generated by Django 2.2.4 on 2019-08-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190816_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_url',
            new_name='author_image_url',
        ),
    ]
