# Generated by Django 2.2.4 on 2019-08-23 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190820_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_authorized',
        ),
    ]
